- name: docker build and push
  hosts: localhost  # Replace with the hostname or IP address of your target server
  become: yes  # Run tasks with sudo privileges
  connection: local
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes   

    - name: Build Docker Image
      command: docker build -t pipeline .
      args:
        chdir: /home/ubuntu/jpetstore1
    - name: tag image
      command: docker tag petstore:latest ghasseen/pipeline:latest 

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
        password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"

    - name: Push image
      command: docker push ghasseen/pipeline:latest

    - name: Run container
      command: docker run -d --name pet1 -p 8081:8080ghasseen/pipeline:latest
